### PR TITLE
Support choosing language model as a configuration

### PR DESCRIPTION
**Pull request by buger**
Fix https://github.com/swark-io/swark/issues/2

----
I found your project via https://helpwanted.dev/
Spread the word about it, to help smaller OSS projects find its contributors :)

### CODE REVIEW

**Comment by ozanani** [comment]
Thank you for the contribution @buger !
I'll spread the word :) 

A few questions:
1. I see that you used enum for the options which makes sense. Will the user also be able to override this with custom value?
In the case new models are available to use and we still haven't updated the enum. 
2. Did you have a chance to test this?
3. Can you please also update the README.md with this new setting? There's a configuration section.

**Comment by buger** [comment]
@ozanani made the change. You can't have editable dropdown with custom options. So I added 2 fields. One is dropdown, and second is text field to override it. This is how it looks:

image
image

And yes, I have tested it and generated some cool diagrams :)

**Comment by ozanani** [comment]
Thanks @buger I'll review it! 😀

**Comment by buger** [comment]
Looks good?

**Comment by ozanani** [comment]
@buger 
Thanks again for your contribution! 
I made a few changes and merged #6 - mainly, I restored your original implementation of a single enum to keep the logic simpler for now. 
Also - both Gemini and o1-preview did not work for me. Was that also the case for you?

**Comment by buger** [comment]
To be frank I tried only Claude 🤔

**Pull request closed without merging**
